; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.61219.0 

	TITLE	X:\GitHub\Renegade\Dragonade_RxD\scripts\HashTemplateKeyClass.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?Get_Hash_Value@?$HashTemplateKeyClass@I@@SAIABI@Z ; HashTemplateKeyClass<unsigned int>::Get_Hash_Value
; Function compile flags: /Odtp /ZI
; File x:\github\renegade\dragonade_rxd\scripts\hashtemplatekeyclass.cpp
;	COMDAT ?Get_Hash_Value@?$HashTemplateKeyClass@I@@SAIABI@Z
_TEXT	SEGMENT
_key$ = 8						; size = 4
?Get_Hash_Value@?$HashTemplateKeyClass@I@@SAIABI@Z PROC	; HashTemplateKeyClass<unsigned int>::Get_Hash_Value, COMDAT

; 18   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 64					; 00000040H
	push	ebx
	push	esi
	push	edi

; 19   : 	return (key >> 20) + (key >> 10) + (key >> 5) + key;

	mov	eax, DWORD PTR _key$[ebp]
	mov	eax, DWORD PTR [eax]
	shr	eax, 20					; 00000014H
	mov	ecx, DWORD PTR _key$[ebp]
	mov	edx, DWORD PTR [ecx]
	shr	edx, 10					; 0000000aH
	add	eax, edx
	mov	ecx, DWORD PTR _key$[ebp]
	mov	edx, DWORD PTR [ecx]
	shr	edx, 5
	add	eax, edx
	mov	ecx, DWORD PTR _key$[ebp]
	add	eax, DWORD PTR [ecx]

; 20   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?Get_Hash_Value@?$HashTemplateKeyClass@I@@SAIABI@Z ENDP	; HashTemplateKeyClass<unsigned int>::Get_Hash_Value
_TEXT	ENDS
END
